version: "3"
services:
  reveda:
    image: reveda:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/machine-id:/etc/machine-id
      - ./config/:/home/caduser/config
      - ./simulations:/home/caduser/simulations
    network_mode: host

